

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.wofhflmboxjilptxhgyl
spring.datasource.password=aB3ni9xA37icqQut

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

constant.key.signer-key=qP7nQdRk5sT2xV8zY3M1Lk9pW2hC0aBnN4UoJtFvE6A=

open.api.title=CuuTro API
open.api.version=v1
open.api.description=API documentation for CuuTro local development
open.api.local-server-url=http://localhost:${server.port:8080}
