# ==== DATABASE (Supabase) ====
app.database.host=${DB_HOST:db.wofhflmboxjilptxhgyl.supabase.co}
app.database.port=${DB_PORT:5432}
app.database.name=${DB_NAME:postgres}
app.database.user=${DB_USER:postgres}
app.database.password=${DB_PASSWORD:duong}
app.database.sslmode=${DB_SSLMODE:require}
app.database.jdbc-url=jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}?sslmode=${app.database.sslmode}

spring.datasource.url=${DB_JDBC_URL:${app.database.jdbc-url}}
spring.datasource.username=${app.database.user}
spring.datasource.password=${app.database.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==== JPA ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
